Repository debrief/pepys-import, pull requests merged in 2020-12, with the labels that each got.

#642 Add Viewer mode
  bin/install_pepys.ps1
  bin/pepys_viewer.bat
  bin/pepys_viewer_training.bat
  create_deployment.ps1
  pepys_admin/cli.py
  pepys_admin/view_data_cli.py
  tests/test_admin_cli.py
Labels: interactive_review

#649 Introduce --skip-validation parameter
  docs/usage.rst
  pepys_import/cli.py
  pepys_import/core/store/common_db.py
  pepys_import/file/file_processor.py
  tests/test_import_cli.py
Labels: Task

#653 Don't print tables twice in Pepys-Admin
  pepys_admin/admin_cli.py
  pepys_import/core/store/data_store.py
  pepys_import/core/store/table_summary.py
  pepys_import/file/file_processor.py
  tests/test_admin_cli.py
  tests/test_data_store_api_postgis.py
  tests/test_data_store_api_spatialite.py
Labels: bug, interactive_review

#651 Remove ability to add reference table entries during import
  pepys_import/resolvers/command_line_resolver.py
  tests/test_command_line_resolver.py
  tests/test_import_cli_end_to_end.py
  tests/test_importers.py
Labels: interactive_review

#662 Ignore pepys archive folder
  .gitignore
Labels: Task

#665 Fix GH Actions interactive review double commenting
  .github/workflows/run_pr_on_binder.yml
Labels: bug, interactive_review

#664 Fix - Stuck in loop adding sensor
  pepys_import/resolvers/command_line_resolver.py
Labels: bug, interactive_review

#666 Add validation to reference search, don't allow user to select something doesn't exist in the suggestions
  pepys_import/resolvers/command_line_resolver.py
  tests/test_command_line_resolver.py
Labels: bug, interactive_review

#654 Add Access to contextual help from Pepys-Import & Pepys-Admin
  migrations/latest_revisions.json
  migrations/postgres_versions/2020-12-01_00116b58f22e_add_helptexts_table.py
  migrations/sqlite_versions/2020-12-01_4bdeb14c63b5_add_helptexts_table.py
  pepys_admin/admin_cli.py
  pepys_import/core/store/constants.py
  pepys_import/core/store/data_store.py
  pepys_import/core/store/postgres_db.py
  pepys_import/core/store/sqlite_db.py
  pepys_import/database/default_data/Help Texts.csv
  pepys_import/resolvers/command_line_input.py
  pepys_import/resolvers/command_line_resolver.py
  pepys_import/resolvers/constants.py
  pepys_import/utils/data_store_utils.py
  pepys_import/utils/text_formatting_utils.py
  tests/sample_data/csv_files/Help Texts.csv
  tests/test_command_line_resolver.py
  tests/test_data_store_api_postgis.py
  tests/test_data_store_api_spatialite.py
  tests/test_data_store_initialise.py
  tests/test_help_texts.py
Labels: Task, interactive_review

#648 Change color of prompt lines
  pepys_import/utils/text_formatting_utils.py
Labels: Task, interactive_review

#680 Fix platform summary
  pepys_import/resolvers/command_line_resolver.py
Labels: interactive_review

#683 Improve Run SQL mode
  pepys_admin/view_data_cli.py
  tests/test_view_data_cli.py
Labels: interactive_review

#674 Show one row for each platform when searching for a platform
  pepys_import/resolvers/command_line_resolver.py
Labels: bug, interactive_review

#685 Use same colours in Pepys Viewer/Admin as in Pepys Import
  pepys_admin/admin_cli.py
  pepys_admin/base_cli.py
  pepys_admin/export_cli.py
  pepys_admin/initialise_cli.py
  pepys_admin/snapshot_cli.py
  pepys_admin/view_data_cli.py
  tests/migration_tests/test_migration.py
  tests/test_admin_cli.py
  tests/test_merging.py
  tests/test_view_data_cli.py
  tests/utils.py
Labels: Task, interactive_review

#691 Don't give the option to search for sensors if none exist on the platform
  pepys_import/resolvers/command_line_resolver.py
Labels: interactive_review

#693 Clarify which datafile is being created
  pepys_import/resolvers/command_line_resolver.py
Labels: Task, interactive_review

#692 Hotfix: Fix bug in #689 where Add sensor option was redirecting to search
  pepys_import/resolvers/command_line_resolver.py
  tests/test_command_line_resolver.py
  tests/test_import_cli_end_to_end.py
  tests/test_importers.py
Labels: interactive_review

#702 Add "Select:" for selecting existing entries
  pepys_import/resolvers/command_line_resolver.py
Labels: Task, interactive_review

#703 Add context help for text questions
  pepys_import/database/default_data/Help Texts.csv
  pepys_import/resolvers/command_line_resolver.py
  pepys_import/resolvers/constants.py
  tests/sample_data/csv_files/Help Texts.csv
  tests/test_command_line_resolver.py
  tests/test_help_texts.py
Labels: interactive_review

#704 Change steps for Add new item
  docs/Pepys Getting Started - Binder.ipynb
  docs/getting_started.rst
  pepys_import/resolvers/command_line_resolver.py
  tests/test_command_line_resolver.py
  tests/test_import_cli_end_to_end.py
  tests/test_importers.py
Labels: interactive_review

#707 Print all error messages in red
  Makefile
  pepys_admin/base_cli.py
  pepys_admin/cli.py
  pepys_admin/export_cli.py
  pepys_admin/snapshot_cli.py
  pepys_admin/utils.py
  pepys_admin/view_data_cli.py
  pepys_import/cli.py
  pepys_import/core/store/common_db.py
  pepys_import/core/store/data_store.py
  pepys_import/file/file_processor.py
  pepys_import/file/highlighter/highlighter.py
  pepys_import/file/importer.py
  pepys_import/resolvers/command_line_resolver.py
  pepys_import/utils/data_store_utils.py
  pepys_import/utils/error_handling.py
  pepys_import/utils/text_formatting_utils.py
  tests/config_file_tests/test_config_file.py
  tests/test_admin_cli.py
  tests/test_data_store_api_postgis.py
  tests/test_data_store_api_spatialite.py
  tests/test_data_store_populate.py
  tests/test_import_cli.py
  tests/test_view_data_cli.py
Labels: interactive_review

#717 Add support for highlighting XML files
  .isort.cfg
  importers/gpx_importer.py
  pepys_import/file/highlighter/highlighter.py
  pepys_import/file/highlighter/support/export.py
  pepys_import/file/highlighter/xml_parser.py
  requirements.txt
  runtime.txt
  tests/sample_data/track_files/gpx/gpx_1_0_Unicode.gpx
  tests/test_load_gpx.py
  tests/test_xml_parser.py
Labels: interactive_review
