Repository debrief/pepys-import, pull requests merged in 2020-11, with the labels that each got.

#608 Make option validation dynamic for platform resolver
  pepys_import/resolvers/command_line_resolver.py
  tests/test_command_line_resolver.py
Labels: bug

#604 Order files before processing
  pepys_import/core/store/data_store.py
  pepys_import/file/file_processor.py
  pepys_import/utils/import_utils.py
  tests/test_importer_utils.py
  tests/test_importers.py
Labels: bug

#620 Don't show default values in Add new XXX options
  pepys_import/resolvers/command_line_resolver.py
Labels: bug

#635 Add interactive demos of PRs
  .github/workflows/run_pr_on_binder.yml
  demos/Demo New Features.ipynb
  demos/_Default Demo.ipynb
  tests/sample_data/track_files/rep_data/sen_frig_sensor.dsf
  tests/sample_data/track_files/rep_data/sen_tracks.rep
Labels: interactive_review

#637 Update GH Actions config to post 'waiting' comment then link
  .github/workflows/run_pr_on_binder.yml
Labels: interactive_review

#633 Make prompt text bold, add new line before printing menu
  pepys_import/resolvers/command_line_input.py
  pepys_import/resolvers/command_line_resolver.py
  tests/test_import_cli_end_to_end.py
Labels: bug, interactive_review

#632 Return to previous menu after cancelling add new platform
  pepys_import/resolvers/command_line_resolver.py
  tests/test_command_line_resolver.py
Labels: bug, interactive_review

#611 Show two different report tables for metadata and measurements and offer menu to users after each file import
  .isort.cfg
  migrations/latest_revisions.json
  migrations/postgres_versions/2020-11-18_35f69a534d88_add_cascading_on_delete.py
  migrations/postgres_versions/2020-11-18_d154cad9087f_add_datafile_id_field_to_changes_table.py
  migrations/sqlite_versions/2020-11-18_5a909b3cec9d_add_datafile_id_field_to_changes_table.py
  migrations/sqlite_versions/2020-11-18_6b92b4b44a5f_add_cascading_on_delete.py
  pepys_admin/export_cli.py
  pepys_admin/merge.py
  pepys_admin/view_data_cli.py
  pepys_import/core/store/data_store.py
  pepys_import/core/store/postgres_db.py
  pepys_import/core/store/sqlite_db.py
  pepys_import/core/store/table_summary.py
  pepys_import/file/file_processor.py
  pepys_import/resolvers/command_line_input.py
  pepys_import/resolvers/command_line_resolver.py
  pepys_import/utils/text_formatting_utils.py
  requirements.txt
  tests/benchmarks/test_import_benchmark.py
  tests/migration_tests/test_migration.py
  tests/test_admin_cli.py
  tests/test_data_store_api_postgis.py
  tests/test_data_store_api_spatialite.py
  tests/test_import_cli_end_to_end.py
  tests/test_importers.py
  tests/test_table_summary.py
Labels: Task, interactive_review

#624 Add training mode
  bin/install_pepys.ps1
  bin/pepys_admin_training.bat
  bin/pepys_import_training_sendto.bat
  demos/Demo Training Mode.ipynb
  pepys_admin/cli.py
  pepys_import/cli.py
  tests/benchmarks/test_highlighter_benchmark.py
  tests/benchmarks/test_import_benchmark.py
  tests/sample_data/track_files/other_data/ASW Data Format2.doc
  tests/sample_data/track_files/other_data/e_trac.txt
  tests/sample_data/track_files/other_data/e_trac_bad.txt
  tests/test_admin_cli.py
  tests/test_import_cli.py
  tests/test_view_data_cli.py
Labels: interactive_review
